### ISSUE TITLE
Masking the alignment

### ISSUE THREAD

**Issue by fbeghini** [biobakery/uniref_annotator#1]
Hi @franzosa ,
In order to better simulate the UniProt's BLASTP behaviour, diamond should be run with `--masking 0`.
Also, why is it considered the minimum of the query and subject coverage in order to assign the  UniRef cluster to the hit? Should it be `qlen/slength >= 0.8`?
https://github.com/biobakery/uniref_annotator/blob/e722bd6ab3f607a64f67f0919c55af8eb6c1b853/uniref_annotator.py#L139

**Comment by franzosa** [comment]
Hi @fbeghini - Interesting point about the masking. I was trying to simulate the UniRef clustering process, and I'm honestly not sure what they did for masking there. Can you point me to something that says they ignore masking of repeat regions? If so I agree we should set `--masking 0` in DIAMOND.

Re: length vs. coverage - We want the shortest member of a UniRef cluster to cover >80% of the longest member/seed. However, because DIAMOND is performing local alignment, if we only compare the query and subject lengths, we risk accepting a strong, short alignment between two larger sequences. By checking coverage I am requiring a more global alignment between the two sequences, i.e. the shorter sequence must COVER 80% of the longer sequence.

Note that this approach is an approximation as well since the 80% criterion is established against the UniRef cluster SEED but we are aligning to the representative sequences. It was a lot more convenient to work with the representatives since we already have them pulled out. There is some risk though that we'd accept a sequence X with 80% coverage of the representative which in turn only had 80% of the seed, meaning that X would not cover the seed at 80%.

**Comment by fbeghini** [comment]
Hi @franzosa 
>Can you point me to something that says they ignore masking of repeat regions? If so I agree we should set --masking 0 in DIAMOND. 

I have not found any paper describing this, but it was coming from a mere observation of the same alignment perfomed with BLASTP and DIAMOND (with and without `--masking`)

**Comment by franzosa** [comment]
I finally tested this as part of bioBakery 4 work and didn't see a big difference with masking on/off when trying to reproduce known UniRef90 -> UniRef50 annotations. I also tested whether using the UniRef seeds vs. the representative sequences helped, and it didn't. It is still noteworthy that the "correct" UniRef50 is not the top hit ~30% of the time. I would like to improve that.
